In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
data = pd.read_csv('eth_data.csv')
data.head()

                                                                                                                                       https://www.CryptoDataDownload.com
unix          date                symbol   open          high          low           close         Volume ETH      Volume USDT                                 tradecount
1630713600000 2021-09-04 00:00:00 ETH/USDT 3938.11000000 3947.70000000 3913.62000000 3946.59000000 6635.24210000   26081128.32748000                                28103
1630627200000 2021-09-03 00:00:00 ETH/USDT 3785.82000000 4027.88000000 3705.05000000 3938.11000000 655903.75739000 2557662974.33001620                            1678132
1630540800000 2021-09-02 00:00:00 ETH/USDT 3826.82000000 3836.80000000 3717.04000000 3785.82000000 525165.79960000 1981758437.08575600                            1402190
1630454400000 2021-09-01 00:00:00 ETH/USDT 3429.19000000 3842.00000000 3382.22000000 3826.82000000 845759.95868000 3038498667.85423990                            2022132

In [33]:
data.reset_index()

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,https://www.CryptoDataDownload.com
0,unix,date,symbol,open,high,low,close,Volume ETH,Volume USDT,tradecount
1,1630713600000,2021-09-04 00:00:00,ETH/USDT,3938.11000000,3947.70000000,3913.62000000,3946.59000000,6635.24210000,26081128.32748000,28103
2,1630627200000,2021-09-03 00:00:00,ETH/USDT,3785.82000000,4027.88000000,3705.05000000,3938.11000000,655903.75739000,2557662974.33001620,1678132
3,1630540800000,2021-09-02 00:00:00,ETH/USDT,3826.82000000,3836.80000000,3717.04000000,3785.82000000,525165.79960000,1981758437.08575600,1402190
4,1630454400000,2021-09-01 00:00:00,ETH/USDT,3429.19000000,3842.00000000,3382.22000000,3826.82000000,845759.95868000,3038498667.85423990,2022132
...,...,...,...,...,...,...,...,...,...,...
1477,1503273600.0,2017-08-21,ETH/USDT,299.1,346.52,294.6,323.29,5134.54,1661944.36,NaN
1478,1503187200.0,2017-08-20,ETH/USDT,290.91,300.53,282.85,299.1,2469.49,730800.66,NaN
1479,1503100800.0,2017-08-19,ETH/USDT,293.96,299.9,278,290.91,2140.08,618248.58,NaN
1480,1503014400.0,2017-08-18,ETH/USDT,302,311.79,283.94,293.96,9392.79,2815460.24,NaN
1481,1502928000.0,2017-08-17,ETH/USDT,303.61,312.18,298.21,302,6155.32,1890017.53,NaN

In [44]:
type(data)
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1482 entries, ('unix', 'date', 'symbol', 'open', 'high', 'low', 'close', 'Volume ETH', 'Volume USDT') to ('1502928000.0', '2017-08-17', 'ETH/USDT', '303.61', '312.18', '298.21', '302', '6155.32', '1890017.53')
Data columns (total 1 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   https://www.CryptoDataDownload.com  1358 non-null   object
dtypes: object(1)
memory usage: 418.7+ KB

KeyError: 'level_0'